language: node_js
node_js:
  - 6
  - 7
rvm:
- 2.2.3
dist: trusty
sudo: required
install:
- npm install
cache:
  directories:
  - node_modules


before_script:
script:
- npm start
- npm test
notifications:
  slack:
    secure: "OjOh8gZjrFgDpQTy1EWm8y4HvPM1p1WVXriq0eXW6mHAPaz64O1sowDqjQIsUlLNhSoq6W4SAVMrVUXj9RRhtxitrM4IOYlrV6gaJHFEXFxtl5ar69XM+dPrffjeZIPuLdvhPmZj776kGnVRogcAn4eupVSAs++VKYDFyTppJlgalijNAU+YkfD6mpdMNSsmurIpXcdaMFwtAF3NMgRix9iq2nKJk/p/6tRTivQyoI8l7gCVEqJ3/1Q65ZCR03XPRZRJcFGVScWLVH6L13v5WczxpD3R6nMWCH/T4WT1+oud7KXQqYbulSlJH9aIfnN7kK6/0FHnhqwZ2WKyCNVtlYrU8Bnw65YLn4TCrWZpyDXmEUSnP+c/JwUvkxP4K1PWzjYnGVzHJjzkC7SmvQmt/n4SSbX2D5zgmCXuRpr1VTzOLGihZis+viid/fso7Ch8uXFqGf5OOIfg0Q3U+v8QfstR0i7jcXjwHXIVjk2FpgKDamiAa2zERQKLDotWz476NC+GvGgakbFm3hLrVREFpfYXDb4/R6vuNcCz5xCjGb3vDBdjUWAXUTvZ1F0z5G/08x4kqoPgupIDXc7n6kv90eZpTOuZBy9VicKJmaditsJQXgnZzXnhI/aB/Lv246F5fL2sVimQthFcvZ3ikXhw2ItIOKMwuSsfLTOwgRaifXg="
