language: node_js
node_js:
  - 6
  - 7
dist: trusty
sudo: required
install:
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install react-transition-group
  - npm install -g serve
addons:
  firefox: "46.0"
cache:
  directories:
    - node_modules


before_script:
script:
  - npm run build
  - serve -s build
notifications:
  slack:
    secure: "vLN2ZTWJqtWZhHAydchetefR"
