language: node_js
node_js:
  - 6
  - 7
dist: trusty
sudo: required
install:
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install react-transition-group
  - npm install -g serve
addons:
  firefox: "38.4.0esr"
cache:
  directories:
  - node_modules

before_script:
  - npm run build
script:
  - npm test
notifications:
  slack:
    on_success: always
    on_failure: always
    secure: t0FSxb2T43vkEnqd0zqRI20lfiM0e2TilSX11E4JFxVNZ7tuRPU1cM8dOHdy4JUd12nR0s4cgQnKtp1YjxhLtwzk18vR5JH7yfPUwrQo/dlvXuygs4ya7Jem5Z8EOjI9Ko2jcCQCgme
37gaUIb8Dcht0/BTCnflf6E+6UO7ikanFuJkmTGFLmhb58x0qrnwFd+06yjQEIHmTzoGJm5ufus6SzEJERsKxsxy9CFluIQQwIWiIfD/1Rh9zXwp7mXvJaR4BNXT4gF0YDmjLzDAq8FU4iRdDIs2OF
QV+heLtuI/9bc2rSigPSMQ6BddJA4iJDz7Qi2NO6AN6TaHJCdcs0iphQDnethLuH1Eg9NJfFTOEBAUl1YooQcvxtIpdVxINQhxzMasqg+xVsbEAQbY4/RDtFGfrXgUoYr9boohbPskK/FOH48rSjdW
tOaUuxUAwULlwq8ItAjZG6wTxY+X7Me0tuUw5Wt9ucvWi5Vo6Rb3e2Dp/vs5jWZvt5RrfjAjkjaVLAYq4GaN82+fBqm6XzdlFENjIkyO1k9WIYtfZ6FOpMSdJ8QNRAElqNpUDJsy6Xn+Hcs+9G4G/q
ps4lj/QypDBcA1//4Jr2YcHlIx39fzLrjFGsOaCVYttBWGhutWJIW4LN4qKOgCH1jLPLlSHQRsaV6UJOggkDfI3OA6NX7M=
