language: node_js
node_js:
  - 6
  - 7
dist: trusty
sudo: required
install:
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install react-transition-group
  - npm install -g serve
addons:
  firefox: "38.4.0esr"
cache:
  directories:
  - node_modules


before_script:
  - npm run build
  - npm test
  # - serve -s build
script:
notifications:
  slack: 
    travisci: "vLN2ZTWJqtWZhHAydchetefR"
