language: node_js
node_js:
- 6
- 7
dist: trusty
sudo: required
install:
- nvm install stable
- nvm use stable
- npm install
- npm install react-transition-group
- npm install -g serve
addons:
  firefox: 38.4.0esr
cache:
  directories:
  - node_modules
before_script:
- npm run build
script:
- npm test
notifications:
  slack:
    secure: LDE4nUwLc83V3VYXhot9OWiaLjKCgW3knluQd2HD8/cBbmqHIk/WKSfZ1OeiL5sdxAfkKKEHUOwP7RgioNBGEeAu8nJrMEOB56+VMZHe0XJHZwR5p4oVZK6CxHy3syyGi4s34QN2mbfdShw8hrJs7gH0I+O7O6zg0mqUki2a1IJq7qeeb1dU7VCZ7U+nrwEJ4d0GKFlhwfgULnCIsRq5iumztfnt+fusk1qQ4EoQXIISWVyNyaoXtERUFU1RfUuFAXWdb3DZFqC5WhGgeGXegp2EOWU4WMqjHgRZMjdfgaUpQhHjrorvA+5AFlwVfWg6eePuCZ/ahC+R04aBA0FQ3f8z8nj/Lq4mbhCSpz1bQh7du49rjIntoHMgT1egL5vWoBEa1vWq6yl8fV78DjpRUWsHD7V5rqn65VRyq4dvzFK/i2UeF6ubplIYYQ//FJ3M3s61Ij+gu2y5IBDhizMDC+x0JbrgGVBuxJMypvfUmM0aW/rGZHxcNjHUnGUT+rG+n2NszCTeBaasRnSRDMP0dm5qGIwLBnHp8qZfbpT+njr7LkxJ1jB1HR/W6MRwnSJxrsKzT9A2GEYD5DmotVdmngrjq59rJQyM/OnVUniIjdDPXwjl/36fqPjD5C0N00z4w3Zg5uWDdmVF3rvM75A/EIxdK06BiQ9KPpJ9uNNGoT0=
