const GET_HOME_POSTS = 'posts/GET_HOME_POSTS';
const GET_FOR_YOU_POSTS = 'posts/GET_FOR_YOU_POSTS';
const GET_SAVED_POSTS = 'posts/GET_SAVED_POSTS';
const GET_SOURCE_POSTS = 'posts/GET_SOURCE_POSTS';

export {
  GET_HOME_POSTS,
  GET_FOR_YOU_POSTS,
  GET_SAVED_POSTS,
  GET_SOURCE_POSTS,
};
